version: "2"
services:
  nginx:
    build: ./nginx
    ports:
      - "8000:80"
      - "8001:443"
    depends_on:
      - app
    volumes_from:
      - app
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  app:
    build: ./app
    depends_on:
      - db
    volumes:
      - ./app/public/wp-config.php:/var/www/html/wp-config.php
      - ./app/upload.ini:/usr/local/etc/php/conf.d/upload.ini
      - ./app/public/wp-content/themes/corydoras:/var/www/html/wp-content/themes/corydoras
      # - ./app/public/wp-content/uploads/*:/var/www/html/wp-content/uploads/*
      # - ./app/public/wp-content/uploads:/var/www/html/wp-content/plugins

  db:
    image: mariadb:latest
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/dump/mysql.dump.sql:/docker-entrypoint-initdb.d/install_wordpress.sql
